### ISSUE TITLE
Document L11 content types somewhere, possibly don't use content_type 4 in the default JSON

### ISSUE THREAD

**Issue by GabeBlincoln** [quietvoid/dovi_tool#110]
https://professionalsupport.dolby.com/s/article/Dolby-Vision-IQ-Content-Type-Metadata-L11?language=en_US

Linking to this would be fine, but a mention that it only works on DV IQ devices (most LG TVs, at least) could be worth a mention.  It doesn't seem to do anything on devices that don't support that.

content_type 4, by their description, is probably appropriate for something like my regular FHD BluRay re-encodes which I'd put in the category of not having the capability of a professional camera, but for UHD BluRay conversion to profile 8 without a re-encode which I'm guessing most people are using (just as it seems like all I ever see are people talking about LG OLED panels which support IQ) content_type 1 is probably more appropriate.    

It's funny that Dolby seems to think that content_type 4 would be a naturally occurring situation since they don't provide any means for "user generated content" shot on non-professional cameras to actually have metadata without spending more than the cameras in that category cost on a mastering display and their tools.  Even owners of the iPhones that shoot in the weird HLG profile can't actually edit the videos aside from cutting and splicing pieces together using MKVToolNix or similar without breaking the metadata using any tool that comes with their computer and still need the mastering display to add it back.  

Thanks to you and others we can do this, but it's somewhat hilarious that they threw that in.  Their website is filled with stuff like that though, I feel like if I clicked enough blog links on their site there'd be one titled "1 Weird Trick to add DV Metadata to Your Cellphone Videos That We Don't Want You to Know!" that would probably just link to this repo.

Similarly that page seems to indicate the white_point is an enum, but the only values they list are 0 for D65 and 8 for D93.  I can't for the life of me imagine when a D93 white point would be appropriate for anything,  but if Dolby is calling it a common mastering display value I'm not one to argue.  For any source that didn't already include L11, it probably shouldn't be set to anything but 0.

**Comment by quietvoid** [comment]
L11 is documented in the [editor documentation](https://github.com/quietvoid/dovi_tool/blob/main/docs/editor.md).
Other use cases require the user to understand the metadata levels, such as adding arbitrary metadata blocks in generation.

I'm assuming they can also do their research.

**Comment by saindriches** [comment]
> Even owners of the iPhones that shoot in the weird HLG profile can't actually edit the videos aside from cutting and splicing pieces together using MKVToolNix or similar without breaking the metadata using any tool that comes with their computer and still need the mastering display to add it back.

The User-generated content, or UGC, exactly means video content shot on these non-professional devices, and the L11 block with `content_type: 4` is already present in video files shot on iPhone since iOS 15. Websites like Vimeo and bilibili allow users sharing videos with Dolby Vision Profile 8.4. For dynamic metadata, it’s a automated process for profile 8.4, no need (and no way) to manually trim it. You can edit them as normal HLG, and supported encoders (FCP / Compressor on MacOS, some apps on iOS) will analyze content to regenerate new metadata when you export videos. In 8.4, only L1, L3 and L4 are dynamic based on analyzing, other values are fixed presets.

> I can't for the life of me imagine when a D93 white point would be appropriate for anything

FYI, D93 is common (and probably only) in Japan, accepted as TV broadcast standard, actually it caused confusion to some people there, who would think D65 standard monitors are too reddish, as they may already used to D93 whitepoint on TV, and many of content is graded with that standard. So it’s not surprise to see a metadata field for it, use D93 may be the proper setting for some Japanese content, instead of D65.

**Comment by GabeBlincoln** [comment]
Thanks for that bit of trivia on D93.   

Apple must have fixed things for re-generation, the original docs I found on Apple's site months back said that it could output the original RPU for use in (?) but any edits were destructive and would remove DV from the output.

**Comment by ValZapod** [comment]
> already used to D93 whitepoint on TV

That is not TV whitepoint, that is ambient light whitepoint. And Netflix converts D93 anime to D65 anime (as if you are watching under D65 dim room). That is all part of BT.1886's reference conditions spec. See article on 709 on wikipedia, I wrote it there long time ago. :)

Dolby Vision IQ is defined in the patent. It is very complex 💩. After all absolute PQ was never supposed to be ambient light controlled.
https://patents.google.com/patent/WO2018119161A1/en
https://patents.justia.com/patent/20190378327

**Comment by GabeBlincoln** [comment]
I'd love to know what light source produces D93 ambient.  I found HID lamps, and that was about it.  :D

I'm sure if I bounced the 1W blue laser into a pile of europium orange phosphorescent powder I could get something in that range for a while before I went blind from scattered laser reflections in the dark room. :P
