### ISSUE TITLE
question regarding P7->P8.1 conversion

### ISSUE THREAD

**Issue by gacopl** [quietvoid/dovi_tool#111]
Hi thanks for this great tool
I am unsure in terms of quality wise what is more superior P7FEL vs P8.1 ? also is P7MEL exactly the same (quality wise) to P8.1
When we do -m2 convert --discard to p8.1 i know that RPU gets converted, but what happens to MEL and FEL, FEL is discarded right? But is MEL data used to create that P8 RPU ?
I understand that if i have P7FEL its better to leave it like that (assuming player supports it) or convert to P8.1 but keep EL.hevc handy for future conversion, while P7MEL can be converted to P8.1 and there's no quality loss, right ?
I mean MEL is just RPU for P7? I saw some MEL tracks that are bigger than RPU extract like 2Mbit/s bitrate on EL i think i read somewhere MEL has some gray plane encoded what happens with to conversion to P8.1

Thanks

**Comment by quietvoid** [comment]
Profile 7 FEL has extra information that cannot be kept in the RPU on its own, it requires the separate video stream.
However it requires the player/device to actually make use of that stream. Only Blu-ray players are expected to support this.

For MEL, it is equivalent to profile 8.1 when converted using `dovi_tool`.
Only the enhancement layer is discarded, because it makes no diference in that case.

> I mean MEL is just RPU for P7

Yes.

**Comment by gacopl** [comment]
And IN case of FEL, if I keep FEL, and later on extract BL+RPU from P8.1 demux it to BL, can i remux them back to BL_FEL_RPU for profile 7 single track or i will have to do double track then?
I have one bluray player that supports 7FEL, but rest my devices can do only 8.1

Also are donations possible :) ?

**Comment by quietvoid** [comment]
> can i remux them back to BL_FEL_RPU for profile 7 single track
No, FEL RPUs contain additional data that is not kept when converting to 8.1.

> Also are donations possible :) ?

No.

**Comment by ValZapod** [comment]
> Only Blu-ray players are expected to support this.

And LG C9.
