### ISSUE TITLE
Enhancement to merge streams

### ISSUE THREAD

**Issue by Nico83500** [quietvoid/dovi_tool#128]
Hi, 
Is it possible to add a feature to merge raw BL + EL tracks to a single track (BL+EL+RPU or BL+RPU so profile 7 or 8), like yusesope's tool ?
Thanks !

**Comment by quietvoid** [comment]
Sure, eventually.

**Comment by manuelrn** [comment]
One thing to keep in mind: Would it be possible to do it exactly like yusesope's tool does?

I mention it because on several occasions I have seen reports from some users indicating that they have problems with the video generated by MakeMKV but with the video generated by yusesope's tool they have no problems.

Apparently MakeMKV doesn't add Access Unit Delimiters and yusesope's tool does it. And maybe there are other differences too...
<br/>
It has been discussed many times in the MakeMKV forums, and it has also been discussed in the tsMuxer repository (https://github.com/justdan96/tsMuxer/issues/450).

Thanks!

**Comment by quietvoid** [comment]
I'm aware of this, it would be an option, probably default.

**Comment by manuelrn** [comment]
> I'm aware of this. It would be an option, probably default.

Great, thank you very much for everything!

One question, does dovi_tool currently add Access Unit Delimiters when injecting a RPU? Or in the current versions does it act in the same way as MakeMKV?

Or does that problem not affect a simple RPU and only affect EL+RPU?

**Comment by quietvoid** [comment]
No, AUD NALUs are not added when injecting.

**Comment by Nico83500** [comment]
Great, thank you !

**Comment by manuelrn** [comment]
> No, AUD NALUs are not added when injecting.

Okay, thanks for the clarification. I already thought not, but I wanted to make sure.

I thought that dovi_tool did not add AUD NALUs due to the fact that in my player during playback of MKV files, sometimes there is a brief pixelation at some random points (it happens very rarely, maybe about 2-3 times throughout the whole movie, sometimes it doesn't even happen).

And I have tested and this problem occurs with videos generated with MakeMKV and dovi_tool, but coincidentally it has never happened with videos generated by yusesope's tool.
<br/>
So it would be very useful if dovi_tool could be able to inject RPU and also EL+RPU, and in both cases also add AUD NALUs.
Everything could be done using only this dovi_tool.
<br/>
Is there an ETA for this feature?
There is no rush, it is simply to know if it could be soon or if it will take some time.

Thanks and regards!

**Comment by quietvoid** [comment]
> So it would be very useful if dovi_tool could be able to inject RPU and also EL+RPU, and in both cases also add AUD NALUs.

I guess.

> Is there an ETA for this feature?

Not really.

**Comment by manuelrn** [comment]
> > So it would be very useful if dovi_tool could be able to inject RPU and also EL+RPU, and in both cases also add AUD NALUs.
> 
> I guess.
> 
> > Is there an ETA for this feature?
> 
> Not really.

Ok, thanks for your quick response.

One proposal, in case the AUD NALUs issue were faster and easier to implement than the other (EL), would it be possible for now to keep only the RPU but add the AUD NALUs to the injection process?

That is, first implement only the AUD NALUs and later implement the injection of the EL.

In this way, for the people who are affected by the issue of AUD NALUs, we would have the possibility of injecting RPU with your dovi_tool and EL with yusesope's tool (until in the future your dovi_tool also implements it).

Thanks!

**Comment by GabeBlincoln** [comment]
Just chiming in that I've seen this rarely on my original 4k TV, an LG Nano 85 (not pixelation, but stutter) but it never happens on an A1 (built in player).  Sometimes ffmpeg seems to break the stream when extracting, sometimes (with high bitrate files converted to 8.1) the TV hardware just isn't fast enough.   The perfect example is halfway through John Wick 3 or in any of the Transformers movies (I add rifftrax audio to those, they're intolerable without it) where bitrates can spike badly in spots.     I remux everything to m2ts after injecting and found that ffmpeg incorrectly extracts the HEVC stream from some MKV files, but TSMuxer extracts a working version.  It might be worth trying that as a stop-gap in the meantime.  If a transcode is being done you can just tell x265 to insert AUDs  and it solves the problem just as well, even if the bitrate isn't massively decreased by the chosen CRF.   LG never updates their manuals and claims DoVi videos have a max bitrate of 50Mb/s, but the A1 only seems limited by the 100Mb/s ethernet port and I've yet to encounter a disk that exceeds what that can provide.

**Comment by quietvoid** [comment]
@manuelrn Implemented the addition of AUD NALUs in the injector: https://github.com/quietvoid/dovi_tool/commit/b9eee5282833d6d8d1d892b5a1587bbf5e27131f

**Comment by manuelrn** [comment]
Thank you very much @quietvoid, great job!

**Comment by Nico83500** [comment]
Thanks for the work !

**Comment by manuelrn** [comment]
@quietvoid when do you plan to release a new version that includes this change (AUD NALUs)?

I imagine the idea is to create a new version together with #139 which I have seen failed checks at the moment.

**Comment by quietvoid** [comment]
> I imagine the idea is to create a new version together with #139 which I have seen failed checks at the moment.

Yes, it's incomplete as I'm still working on it.

**Comment by manuelrn** [comment]
> > I imagine the idea is to create a new version together with #139 which I have seen failed checks at the moment.
> 
> Yes, it's incomplete as I'm still working on it.

Okay, thanks again!

**Comment by quietvoid** [comment]
It's now possible to mux BL+EL into a single HEVC stream. The behaviour by default is slightly different to MakeMKV and yusesope's tool.
See doc: https://github.com/quietvoid/dovi_tool#mux

I've tested with some files I have on hand, and using `--eos-before-el` results in identical bitstreams to yusesope's output.

I still have some changes I want to add in before making a new release, but I'll add the binary link when it's ready.
Testing is welcome.

**Comment by manuelrn** [comment]
Thank you very much @quietvoid!

A newbie question, can the EOS/EOB NALUs also be written with RPU only (without EL)?
To replicate the behavior of yusesope's tool also with only RPU.

Although I assume not since that flag seems not to be available for the inject command, only for the mux command.

**Comment by quietvoid** [comment]
> A newbie question, can the EOS/EOB NALUs also be written with RPU only (without EL)? To replicate the behavior of yusesope's tool also with only RPU.

When muxing, they are always written when present in the base layer HEVC stream.
The behaviour is the same regardless of `--discard` or not.

By default, end of sequence/end of bitstream (EOS/EOB) NALUs are written after every NALU from the base layer AND after every EL NALU (including RPU).
With the `--eos-before-el` flag, the EL+RPU are written after EOS/EOB. Like MakeMKV, yusesope do.

> Although I assume not since that flag seems not to be available for the inject command, only for the mux command.

It is not relevant to the `inject-rpu` subcommand because that always writes the RPU after the last slice NALU of the AU (read frame).
The EOS/EOB NALUs are always after the last slice, therefore the RPU is always written before them.

**Comment by quietvoid** [comment]
It does turn out that the build I sent does affect RPU placement for the last frame when a EOS or EOB NALU is present.
I've fixed it in #145.

**Comment by quietvoid** [comment]
This is now in release 1.5.0: https://github.com/quietvoid/dovi_tool/releases/tag/1.5.0

**Comment by Nico83500** [comment]
Thanks a lot @quietvoid I'll try it very soon !
