### ISSUE TITLE
Missing frame/slices for metadata! Decoded index 53030

### ISSUE THREAD

**Issue by Harybo** [quietvoid/dovi_tool#129]
So I'm extracting the rpu from several episodes of a series but one episode is giving me problems.

It shows me the following error

![image](https://user-images.githubusercontent.com/29784405/159969455-3b233e7a-8770-40fc-a09b-03b553a9db39.png)

**Comment by quietvoid** [comment]
Thanks. I can reproduce the issue.
Not sure when I'll have the time to look into it.

**Comment by Harybo** [comment]
ok np

**Comment by Harybo** [comment]
Have you had time to test or not yet?

**Comment by quietvoid** [comment]
No

**Comment by ValZapod** [comment]
You know metadata from Hollywood is not perfect. There is one episode of Falcon that has strange brightness bug in RPU and there is also a strange bug in Ron, in BL.

**Comment by quietvoid** [comment]
This is definitely an invalid file issue.
There are two duplicate NALUs present after a frame's RPU: another RPU NALU and a SEI suffix NALU.

The solution is to ignore the duplicate RPUs when extracting.
This is the way FFmpeg handles it as well.

Unfortunately, since the NALUs are only parsed when extracting, this means demuxing or converting does not discard the duplicates.
This isn't something I'm interested in fixing, because it only happens for invalid files.
Pull requests welcome.

**Comment by clidx** [comment]
I have a similar problem on the latest build but not exactly the same. Is it an evolution of this issue?
![image](https://i.ibb.co/ypgP7jq/Untitled.jpg)

**Comment by quietvoid** [comment]
Seems to be the same issue, there are many warnings though.
