### ISSUE TITLE
How to go about converting DoVi RPU to HDR10+ metadata?

### ISSUE THREAD

**Issue by sagz** [quietvoid/dovi_tool#23]
Following up from [the previous issue thread](https://github.com/quietvoid/dovi_tool/issues/22), here's the overall goal. I'm trying to upload a bunch of content I have to Wikimedia Commons but that [requires royalty-free encoded videos](https://commons.wikimedia.org/wiki/Help:Converting_video). I can do the HEVC>VP9 while maintaining BT.2020 (pending tone-curve conversion if needed), but the frame-level dynamic metadata gets lost in the process.

The thing is that iPhone12, while being DoVi encoded video, is HLG and so it seems like the metadata conversion from DoVi RPU to HDR10+ JSON should be possible 'easily' enough...

I'm not sure if it's in-scope for `dovi_tool` to do this, but since you also are the creator of the [amazing](https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/) [`hdr10plus_parser`](https://github.com/quietvoid/hdr10plus_parser), I thought I'd go to you first to ask how to connect these two standards.

Looking through[ the extracted frame info from a DoVi RPU](https://gist.github.com/sagz/a39f4bdec45c2f4ae9e7f7764c46db26) and [a sample of the HDR10+ json from Tears of Steel](https://bitbucket.org/multicoreware/x265_git/downloads/), I don't think it's just a matter of reformatting the json... or is it?

Thanks for you help!

**Comment by quietvoid** [comment]
No, the two formats are different.
There are patents on converting from one to another but the detailed steps are not public.

Since neither HDR10+ or Dolby Vision analysers are publicly available, this isn't a trivial task.
And I don't plan on looking into this at all.

**Comment by RonRicoSuave** [comment]
I know you closed this but it's also my understanding that HDR10+ requires the source video to be HEVC with HDR10 / SMPTE 2084 anyway.   Dolby vision only allows AVC for one profile and requires HEVC for the rest
(See https://hdr10plus.org/wp-content/uploads/2019/08/HDR10_WhitePaper.pdf )
Dolby have backwards compatibility exceptions built into DV for broadcast purposes, mainly.

I attempted to download two different HDR10+ videos from youtube with youtube-dl and the resulting .webm files didn't contain any HDR10+ metadata, which makes sense since it isn't compatible with VP9...

**Comment by quietvoid** [comment]
HDR10+ with VP9 relies on the container for the metadata, it is not in the stream.
I don't know if Youtube videos are HDR10+ when played on a supported display.

**Comment by RonRicoSuave** [comment]
Thanks, I wasn't aware of that, I'll look into it further.  I was definitely getting the HDR versions despite not having an "HDR-capable" display on my PC, and because of the nature of youtube-dl it would have pulled the highest resolution version possible.  If it's container-level it could be that ffprobe looking at frames and mediainfo both missed it, and hdr10plus_tool doesn't operate on .webm containers.

**Comment by Gronis** [comment]
I can see that it is possible to create a dolby vision RPU using HDR10+ metadata json file, so there seem to be some compatibility between the formats.

**Comment by sagz** [comment]
Is the image processing easy to do? aka, there's a set formula to calculate
the histogram? considering that decode speeds are so good and in so many HW
devices, that shouldn't be too hard to do for users with all sorts of
computers if they wanna convert.

**Comment by quietvoid** [comment]
It shouldn't be too complicated. There's no public reference or implementation though.

**Comment by joaoserra** [comment]
> There are patents on converting from one to another but the detailed steps are not public.

Patents on converting DV metadata to HDR10+? I understand that the patents don't have the exact details, but exactly what patents? I would like to take a look at those.

Thanks!

**Comment by quietvoid** [comment]
I didn't keep a note of it.
