### ISSUE TITLE
Inject DV into existing hdr10 file?

### ISSUE THREAD

**Issue by koolkunz** [quietvoid/dovi_tool#24]
Can this tool be used to inject dolby vision from the bluray/remux to an x265 hdr10 encode ?

If yes, please explain a little how?

**Comment by quietvoid** [comment]
If you have the source you should just be using the RPU for the encode.

Otherwise you extract the RPU and use the command in the readme:
`dovi_tool inject-rpu -i x265-encode.hevc --rpu-in RPU.bin`

**Comment by koolkunz** [comment]
Sorry to bother you again, one more small question regarding this, what to do in case of an existing cropped black bars h265 hdr10 encode ? I know I need to use the --crop flag but not sure exactly how to use it?

**Comment by quietvoid** [comment]
If you are using metadata for a cropped encode, you should be using --crop either when extracting or when editing.
Example for editing: https://github.com/quietvoid/dovi_tool/blob/main/assets/editor_examples/crop.json

**Comment by koolkunz** [comment]
so I should use the crop flag when extracting RPU from the remux/blu ray disc source and then later inject that rpu into the cropped encode without using the crop flag, right?

**Comment by quietvoid** [comment]
The crop flag doesn't affect the `inject-rpu` command, so yes.

**Comment by koolkunz** [comment]
ok I think I got it.. thanks !

**Comment by koolkunz** [comment]
`dovi_tool inject-rpu -i x265-encode.hevc --rpu_in RPU.bin
Parsing RPU file...
Processing input video for frame order info...
thread 'main' panicked at 'Number of frames of input and RPU file are different!', src\dovi\rpu_injector.rs:140:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

getting this when both the video files are of exact same length. source is a remux, destination is a hdr10 encode

**Comment by quietvoid** [comment]
See this issue for info: https://github.com/quietvoid/dovi_tool/issues/19

**Comment by koolkunz** [comment]
Ah, okay I was using gmkvextractgui only. Will procede with ffmpeg from now on.

**Comment by manuelrn** [comment]
@quietvoid I have a question related to this topic.

If starting from an HDR encode in MKV, not HEVC file. Would it be appropriate to get that HEVC file from the MKV with a UsEac3to demux? (I have doubts after seeing issue #19 with gMKVExtractGUI)

Or could it just do everything at once with ffmpeg?
Something like that:
ffmpeg -i file.mkv -c:v copy -vbsf hevc_mp4toannexb -f hevc - | dovi_tool inject-rpu -i - --rpu-in "file_RPU.bin"
<br/>

And finally, how do I proceed with the resulting file?
Is it necessary to open the file with MakeMKV and then save it again before loading it into MKVToolNix?

I say it because for a long time I think it was necessary to do this, but I have seen that recently you have contributed some commits in the MKVToolNix project that help the implementation of Dolby Vision. Then I don't know if now it could be used directly in MKVToolNix without first using MakeMKV.
<br/>

Thanks and regards!

**Comment by quietvoid** [comment]
Injecting cannot be used with piping, because it relies on the whole decoded order for interleaving metadata.

You can just use ffmpeg to demux, like this: `ffmpeg -i file.mkv -c:v copy video.hevc`
And then use `dovi_tool` using the HEVC bitstream.

After injecting, you can mux the final file to MKV using MKVToolNix v58.
There's no need for MakeMKV.

**Comment by manuelrn** [comment]
Okay, thank you very much for your quick reply!
Regards!

**Comment by koolkunz** [comment]
@quietvoid I tried doing this for a movie (Scott Pilgrim vs the World). Extracted rpu from remux with crop flag using:
`dovi_tool -c -m 2 extract-rpu source.hevc `

then injected that rpu into an hdr10 encode using:
`dovi_tool inject-rpu -i x265-encode.hevc --rpu-in RPU.bin`

and then muxed the hevc file back to mkv along with audio and subtitles using mkvtoolnix. And the resultant file shows dovi profile 8 in mediainfo, but the file does not play via plex.

Anything I am doing wrong here?  (the hevc files have been extracted using ffmpeg command: ffmpeg -i title_t00.mkv -c:v copy video.hevc)

**Comment by quietvoid** [comment]
I don't know, ask Plex.

**Comment by koolkunz** [comment]
It is not just about plex, the file doesnt play on other video players also on an android tv. I just mentioned plex because that is what most people use to play dovi files.

**Comment by quietvoid** [comment]
What do you expect me to do? You didn't prove any sample.
If MediaInfo detects it the problem isn't coming from here.

**Comment by koolkunz** [comment]
Ok thats my bad but I was just asking if anything wrong with the steps I have taken.

**Comment by quietvoid** [comment]
Probably not given both MKVToolNix and MediaInfo has no issue with the file.
