### ISSUE TITLE
Convert P8 to P7 MEL

### ISSUE THREAD

**Issue by ZimuQin** [quietvoid/dovi_tool#44]
Hi! Is there any way to convert from Dolby Vision Profile 8 to Profile 7 MEL currently? I didn't find a way to do this.

**Comment by quietvoid** [comment]
There isn't a way.
I'm not sure what purpose someone would have for this, profile 8 should be the same except the enhancement layer is not required.

**Comment by ZimuQin** [comment]
Thanks very much for your reply! I was just experimenting to make a dual-track P7 MEL mp4 file to see if it can play on my device using Dolby's mp4muxer. However, it seems like it was still recognized as P8. I don't know if this makes any sense to you.

**Comment by quietvoid** [comment]
Well if you used a profile 8 RPU then the flags for the presence of an enhancement layer are not enabled.
Did you encode an enhancement layer yourself?  It would have to be encoded the same as the base layer, which gets complicated since you have to make sure the frame types and order match.

**Comment by quietvoid** [comment]
If you use `dovi_tool info` it will show the profile.
The RPU data doesn't indicate it, it's a combination of the flags to recognize the profile.

**Comment by ZimuQin** [comment]
Thank you so much. I'll keep experimenting your wonderful tool by myself.

**Comment by ZimuQin** [comment]
I managed to modify "disable_residual_flag" and "el_spatial_resampling_filter_flag" in the header, but when I use `dovi_tool info`, I got this error: "thread 'main' panicked at 'assertion failed: !reader.get()', src/dovi/rpu/vdr_dm_data.rs:172:17". So I guess some other parameters also needs to be altered as well. Apparently, it is much more complicated than I thought.

**Comment by quietvoid** [comment]
Yes, there is also the NLQ data to recreate..
When converting to P8: https://github.com/quietvoid/dovi_tool/blob/main/src/dovi/rpu/rpu_data.rs#L105https://github.com/quietvoid/dovi_tool/blob/main/src/dovi/rpu/rpu_data.rs#L105
NLQ struct: https://github.com/quietvoid/dovi_tool/blob/main/src/dovi/rpu/vdr_rpu_data.rs#L24

There are profile 7 RPUs in the assets folder, maybe recreating from the MEL would work.

**Comment by ZimuQin** [comment]
Thank you! I'll keep experimenting.

**Comment by quietvoid** [comment]
Oh yea, some of the files in assets are old and not parsed properly by `info`.
Need to prepend two bytes to the file and edit so that it starts by `00 00 00 01 19 08`

**Comment by ZimuQin** [comment]
Following your advice, I've successfully recreate NLQ data from existing MEL to create a P7 rpu. However, the final file is not playable on my device. It shows no video, only audio, so I guess it is the incorrect encoding of the EL. (It may be too difficult for me to do so with x265)
Again, thank you so much for your great tool!

One small question: I'm a little confused with the "active_area" parameter, because on my device(Oppo UDP-203), it doesn't seem it was properly used to crop the video. If "active_area" is not set on an uncropped video with black bars, would there be any artifacts on the black bar or the content area? Please tell me what is expected, as I actually didn't see anything wrong without the parameter on my device. Thank you!

**Comment by quietvoid** [comment]
For Blu-ray players, Dolby mentions that the active area metadata is ignored because the letterbox bars are used to display subtitles.
Other players might show artifacts but only if there is metadata but the video itself was cropped, as far as I know.

**Comment by ZimuQin** [comment]
That makes sense! Thank you for your patience.

**Comment by ZimuQin** [comment]
After a lot of playing with different parameters, I found that for P7 to work on my Oppo player, I have to set `num_x_partitions_minus1` in the header to 2046 (I found the value in another MEL UHD Blu-ray) instead of the default value 0 for some reasons. If set to zero, the player would just show no video at all. I have no idea what was happening though.

**Comment by quietvoid** [comment]
Someone else asked for this so I implemented it in 5ca27765d8f6a5011bc9bd5ff9ab25251c10b9cc

**Comment by ZimuQin** [comment]
Great work as always!

**Comment by ZimuQin** [comment]
@shroomM2 Are you trying to encode EL by yourself or just inject the rpu into the BL? I found encoding EL very tricky without the use of commercial solutions, because you need to make sure the frame types of each frame in BL and EL are the same. I did somehow make it work on Oppo 203, but the compatibility is in question. I think it makes more sense to just use P8 without EL.

**Comment by shroomM2** [comment]
@ZimuQin I want to encode the EL by myself, yeah.

I don't have a device than can play profile8.1 with TrueHD ATMOS.
Since I want to play this file on an Oppo 203 clone, P8 is (as far as i know) not supported.

My current source is a P8.1 in an MKV. With the help of quietvoid, I managed to track down the corruption - it happened because I used ffmpeg to extract the HEVC stream from this MKV. Now I used mkvextract and the decoding problems went away.

My current approach is:
* extract the hevc from mkv using mkvextract
* demux this hevc using dovi_tool to bl and el
* extract rpu from hevc using dovi_tool and convert it to profile7
* encode an all-black MEL
* inject the profile7 rpu into that using dovi_tool
* mux using tsMuxer in Bluray folder / Bluray ISO

When I encode the EL, I parse the BL, get the frame types, then generate a qpfile and feed it to x265 to encode a 1920x1080 all-black EL.

I actually produced a working PoC file, but need to do more testing using a full length content.

**Comment by ZimuQin** [comment]
@shroomM2 As far as I know, profile 8.1 in TS container is supported on Oppo 203. Just use tsmuxer to re-mux it to TS file would be fine. That's what I've been doing.
BTW, my approach to encode EL is similar to yours, but the problem is that I can't get certain frames the same type as you stated in the qpfile. Maybe the way I got frame types was wrong. I used ffprobe. How do you get all the frame types?

**Comment by shroomM2** [comment]
Oh, I did not know that about the Profile 8.1 support, will check it out, thanks!

My current approach for getting the frame types is using ffmpeg and the `showinfo` filter. The problem is that it's slow, I'm looking into optimizing this.

The CLI is something like...
```
 ffmpeg -i input.mkv -filter:v "showinfo" -f null - 2>&1 | grep iskey > showinfo.txt
```

Which gets me this in the file...
```
[Parsed_showinfo_0 @ 0x7695840] n:   0 pts:      0 pts_time:0       pos:     9694 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:1 type:I checksum:8819896B plane_checksum:[CB24DAF0 444562BB C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
[Parsed_showinfo_0 @ 0x7695840] n:   1 pts:     42 pts_time:0.042   pos:   107238 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:0 type:B checksum:4086779D plane_checksum:[BB33DAF0 050D50ED C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
[Parsed_showinfo_0 @ 0x7695840] n:   2 pts:     83 pts_time:0.083   pos:   106674 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:0 type:B checksum:5E86779D plane_checksum:[D933DAF0 050D50ED C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
[Parsed_showinfo_0 @ 0x7695840] n:   3 pts:    125 pts_time:0.125   pos:   106099 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:0 type:B checksum:4086779D plane_checksum:[BB33DAF0 050D50ED C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
[Parsed_showinfo_0 @ 0x7695840] n:   4 pts:    167 pts_time:0.167   pos:   107804 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:0 type:B checksum:8D79876D plane_checksum:[D933DAF0 0F0D60BD C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
[Parsed_showinfo_0 @ 0x7695840] n:   5 pts:    209 pts_time:0.209   pos:   105521 fmt:yuv420p10le sar:1/1 s:3840x2160 i:P iskey:0 type:P checksum:A7D9896B plane_checksum:[CB24DAF0 640562BB C0084BB1] mean:[64 512 512] stdev:[0.0 0.0 0.0]
...
```

I parse this with a python script, but making sure I use `b` for B-frames as `B` represents a reference b-frame. So something like this...

```
0 I
1 b
2 b
3 b
4 b
5 P
6 b
7 b
8 b
9 b
10 P
```

It's possible my way is not OK either, since I only tested on ~5 minute files, will do more testing.

**Comment by ZimuQin** [comment]
@shroomM2 My way is similar. It did work on Oppo 203 but I doubt it would work on other machines. You can use Dolby Vision Verification Toolkit (https://developer.dolby.com/dolby-professional/professional-products/dolby-vision-verification-toolkit/) to check if your streams are valid. I got a lot of frame type mismatch with my file.

**Comment by Travillion** [comment]
> @shroomM2 As far as I know, profile 8.1 in TS container is supported on Oppo 203. Just use tsmuxer to re-mux it to TS file would be fine. That's what I've been doing. BTW, my approach to encode EL is similar to yours, but the problem is that I can't get certain frames the same type as you stated in the qpfile. Maybe the way I got frame types was wrong. I used ffprobe. How do you get all the frame types?

I saw on another thread that ffprobe identifies multiple frame types as IDR frames, leading to many "false positives." Using the HEVC decoder through ffmpeg produces a more accurate frame identification, thus the method demonstrated by shroomM2 should work better than ffprobe.

**Comment by ZimuQin** [comment]
@Travillion ffmpeg also marks both IDR and CRA as type I keyframes, so it won't work as you expected. There is some very complicated way to get the correct frame types of all frames. However, the problem is that the BL stream was very likely encoded by some commercial encoder, and you are not able to create a compliant EL stream using X265 because of the encoder limitation. Thus, I finally gave up on this and now I am happy with profile 8.1 playback.

**Comment by quietvoid** [comment]
If you're brave enough you can also reencode with the benefits of the FEL.
Using this: https://github.com/quietvoid/vs-nlq

**Comment by Travillion** [comment]
> @Travillion ffmpeg also marks both IDR and CRA as type I keyframes, so it won't work as you expected. There is some very complicated way to get the correct frame types of all frames. However, the problem is that the BL stream was very likely encoded by some commercial encoder, and you are not able to create a compliant EL stream using X265 because of the encoder limitation. Thus, I finally gave up on this and now I am happy with profile 8.1 playback.

Thank you for the clarification on ffmpeg and I frames. Can you point me in the direction of the method to correctly identify frame types? I haven't been able to find any methods besides ffprobe or ffmpeg, which are unreliable.

**Comment by quietvoid** [comment]
> Is there any documentation for this tool? I'm not sure if I'm brave enough, but I would like to look into it.
No, it's meant to be used as a VapourSynth plugin.
I don't provide support for it.

**Comment by Travillion** [comment]
I'll start with VapourSynth then. Thanks!

**Comment by RonRicoSuave** [comment]
Oh nice, I was wanting to do this (implement ETSI GS CCM 001) but was unfamiliar with VapourSynth.   I was looking into implementing it in OpenCL for FFMPEG instead, but it quickly became too complicated for their limited custom filter API the way I was reading things (see below, namely needing to know which plane is being operated on), and I quickly learned that nothing can play 12bpc HEVC properly.  I couldn't get it playing for more than 10 seconds in VLC before the decoder fell too far behind and dropped to 1fps, and the TV didn't recognize the file at all.  Maybe the decoders I tried were just terrible.     The best OLED TVs still can't display all of the P3 color space.  Oddly the lowest end LG has the best coverage, it goes down the brighter they get to just over 80% on the C1 and G1.  Generally that's an indicator that the panel itself doesn't have 10 bits of gradation, which makes higher bit depths seem pointless other than giving the panel a bit more room to manipulate data in...   luma channel maybe?   Certainly not color if they haven't hit 100% P3.

So my reasoning was that I thought the BL had to be mapped into the HDR domain via 5.4.2 using all of the additional RPU pivot data before the EL could be applied to it with 5.4.3?   Your code appears to only be doing the NLQ part (5.4.3) and applying it to the BL.   It seemed as though all the polynomial and MMR data needed to be applied to get the BL into a state that was ready for EL application.  It's possible I missed a key point somewhere in there, or maybe Dolby set things up differently, but your NLQ algorithm being identical to the paper makes me think not... 


Anyway, I was thinking I'd have to do both steps then reduce the bit depth to 10bpc 4:2:0 to get it playing anywhere which might pull some barebones extra data after re-encoding but I couldn't see it being better than just keeping the studio-encoded BL.  Most of the FELs I've looked at tend to be mostly high-frequency detail that would get destroyed at low-bitrate encode settings even with the size amplification from the upscale.   I've yet to run across one of the discs I've read about where the EL contains most of the data due to something being done badly during the mastering process.

**Comment by quietvoid** [comment]
>  It seemed as though all the polynomial and MMR data needed to be applied to get the BL into a state that was ready for EL application.

That is correct. The polynomial and MMR steps are done prior to NLQ, through `libplacebo`, in my case using `vs-placebo`
That isn't included in the `vs-nlq` example.
NLQ processing is also preferrably done in full range (0-255)

As for reencoding, it does indeed lose most of the extra detail but the brightness/chroma benefits from the FEL are still there.

Currently the `vs-nlq` code seems to result in a slightly different color temperature, which I will investigate later.
A couple of people are implementing the ETSI document, discussions are mostly in libplacebo's IRC channel.

**Comment by RonRicoSuave** [comment]
Ah good, I wasn't reading that wrong.   I'll look into those projects and maybe try it on a FEL disk where the extra detail on the far ends is needed;  Jurassic World 2 (+ Rifftrax of course) is a good candidate (possibly the only positive thing ever said about it)  since tons of the movie is extremely dark.   The FEL for it had enough contrast / detail by itself to see most of what was going on in any given scene.

I might revisit the OpenCL mess once ffmpeg fixes using the source of a hardware decode as OpenCL / Vulkan input on AMD cards on windows, but right now there's some broken color format problem.   The slow part of the whole mess is going to be the HEVC encode anyway so it might not be worth it.  

The color temperature thing is odd since all the weird color math is in the previous section...   unless there's something to do with the fun mess of chroma siting that wasn't mentioned in the document (or isn't being handled right in the decoder?).  From what I understand most of the time it barely matters, but BL + FEL is one of the cases where it does.

**Comment by quietvoid** [comment]
Not sure, I haven't looked into it yet.
There are many steps I'm skipping currently: the documented EL resampling, chroma siting.
Here's my last attempt comparison: https://slow.pics/c/Phs22yhT

The noticeably different part is the white dress, where the NLQ filtered image is different.

**Comment by ValZapod** [comment]
> have to set `num_x_partitions_minus1` in the header to 2046

That value is actually two values. num_x_partitions_minus1 is 0

**Comment by GabeBlincoln** [comment]
I'm intrigued by what might be possible with the hardware HEVC Main12 4:2:2 and 4:4:4 that are supposed to be on Intel gen 12 processors.  4:2:2 is obviously great because the proper bitdepth combined BL+FEL stream of a 4k could be encoded and played back, something that everything I've tried just chokes to death on in software.  Why the companies making $2000-6000 MSRP workstation GPUs (or even the $1000 MSRP desktop ones) haven't tacked this on to their feature set (and why Intel added a feature geared towards people who need a workstation processor that won't have an integrated GPU to its consumer line)    4:4:4 would be attractive for collapsing a 2K upscale UHD BL+FEL disk back down to the 2K resolution that it really is   (while removing chroma subsampling altogether aside from the extra 2 bits from the FEL being 4:2:0).  

My reasoning behind this is that both of my 4k TVs do a better job of upscaling 1080p HEVC than the studio did on a huge percentage of the 2k upscaled UHD releases I've seen, and that's from 4:2:0 subsampled sources.    Some companies (*cough* Disney/Marvel *cough*) have _some_ releases that look like somebody saw how long a high quality upscaling algo was going to take to transcode and switched to bicubic or bilinear then stacked 4 unsharp masks on it because their temporal-aware filter was also slow when they'd have been better off using the mythical 1:1 BL:FEL variant allowed on a UHD (but that I've never actually spotted) and letting user hardware  handle the upscale...  

Meanwhile $1000 MSRIP gpus still won't do anything except possibly MAIN10 4:4:4  in some models.  I used to just hate chroma subsampling on general principle, since it should have been abandoned outside of broadcast situations that need it years ago  (main 12 4:4:4 isn't really a massive size increase over regular HDR10 4:2:0, but seeing the HEVC mono profile called 4:0:0 subsampling really solidified that hate for me.  Specifying that chroma channels don't exist should be as simple as calling it Mono, since there's an HEVC profile made for it, but the ridiculous notation had to go and make it   even dumber sounding...  :P

**Comment by ValZapod** [comment]
> seeing the HEVC mono profile called 4:0:0 subsampling really solidified that hate for me.

No, there are two profiles. One that is Y only and one that has Cb Cr as achromatic, 128 for 8 bit, 512 for 10 bit.

**Comment by saindriches** [comment]
> using the mythical 1:1 BL:FEL variant allowed on a UHD

Did you mean FHD? Since 1:1 BL:EL is only allowed in FHD. For HEVC, only Main10 profile is used in current DV profiles, have you tried making a BL+FEL with 4:2:2 or 4:4:4 to playback on TV? It may cause problem.

**Comment by HoffmannTom** [comment]
Hello,
I also have a BL+RPU file and want to convert it into a BluRay disc.
How can I generate an EL / MEL ?
Up to now I extracted the RPU and the BL. With the BL I can create a BD but without the HDR information.
Unfortunately, I dont know the MPEG- and DV-Specification by heart.
Thanks in advance!
